import {
  CefrLevel,
  ExerciseType,
  LearningPackDetail,
  UserProfile,
  WritingSubmissionModel,
  ZoneType,
} from '@lexicon/types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_demo_expedition_01',
  email: 'expedition@lexicon.hu',
  targetCefr: CefrLevel.B2,
  currentCefr: CefrLevel.B1,
  streakDays: 7,
  lastActiveAt: new Date().toISOString(),
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

export const INITIAL_PACKS_DETAIL: LearningPackDetail[] = [
  {
    id: 'pack_it_01',
    title: 'Docker & Containerization Essentials',
    cefr: CefrLevel.B2,
    topic: ZoneType.IT,
    focus: 'System Architecture & DevOps',
    estimatedMinutes: 30,
    vocabularyCount: 4,
    chunksCount: 3,
    exercisesCount: 4,
    createdAt: new Date().toISOString(),
    writingPrompt: 'Írj egy 5-8 mondatos összefoglalót angolul arról, hogy miért elengedhetetlen a konténer-vezénylés (orchestration) és az izoláció éles felhős környezetben.',
    lessons: [
      {
        id: 'les_it_01',
        packId: 'pack_it_01',
        title: 'Konténerek és virtuális gépek összehasonlítása',
        contentMd: `# Bevezetés a konténerizációba\n\nA virtuális gépekkel ellentétben a konténerek nem igényelnek külön vendég operációs rendszert (*guest OS*), hanem közvetlenül a gazdagép Linux-kerneljét osztják meg izolált névterek (*namespaces*) és vezérlőcsoportok (*cgroups*) segítségével.\n\n### Miért nélkülözhetetlen az IT világban?\n- **Konzisztens környezet:** Megszünteti a hírhedt *„de nálam működött!”* (*it worked on my machine*) kifogást.\n- **Gyors indítás:** Másodpercek alatt felállíthatunk (*spin up*) új konténereket.\n- **Erőforrás-hatékonyság:** Sokkal kisebb memórialábnyom és gyorsabb skálázhatóság.`,
        createdAt: new Date().toISOString(),
      },
    ],
    vocabulary: [
      {
        id: 'voc_it_01',
        packId: 'pack_it_01',
        term: 'orchestration',
        phonetics: '/ˌɔː.kɪˈstreɪ.ʃən/',
        translationHu: 'vezénylés, automatizált koordináció',
        definitionEn: 'Automated configuration, coordination, and management of computer systems.',
        collocations: ['container orchestration', 'orchestration tool', 'orchestration workflow'],
        examples: ['Kubernetes is widely used for container orchestration in enterprise environments.'],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'voc_it_02',
        packId: 'pack_it_01',
        term: 'immutable',
        phonetics: '/ɪˈmjuː.tə.bəl/',
        translationHu: 'megváltoztathatatlan, módosíthatatlan',
        definitionEn: 'Unable to be changed over time.',
        collocations: ['immutable infrastructure', 'immutable image', 'immutable deployment'],
        examples: ['Docker containers should be treated as immutable artifacts.'],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'voc_it_03',
        packId: 'pack_it_01',
        term: 'overhead',
        phonetics: '/ˈəʊ.və.hed/',
        translationHu: 'többletterhelés, járulékos erőforrás-igény',
        definitionEn: 'The extra operating cost or computing power required to run a task.',
        collocations: ['low overhead', 'performance overhead', 'reduce overhead'],
        examples: ['Containers have significantly less overhead than full virtual machines.'],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'voc_it_04',
        packId: 'pack_it_01',
        term: 'isolate',
        phonetics: '/ˈaɪ.sə.leɪt/',
        translationHu: 'elszigetel, elkülönít',
        definitionEn: 'To separate something from other things with which it is connected.',
        collocations: ['isolate dependencies', 'isolate processes', 'network isolation'],
        examples: ['Docker allows developers to isolate applications in sandboxed containers.'],
        createdAt: new Date().toISOString(),
      },
    ],
    chunks: [
      {
        id: 'chk_it_01',
        packId: 'pack_it_01',
        phrase: 'spin up a container',
        meaningHu: 'gyorsan elindítani / létrehozni egy konténert',
        contextSentence: 'We can spin up a new Redis container in seconds using Docker Compose.',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'chk_it_02',
        packId: 'pack_it_01',
        phrase: 'out of the box',
        meaningHu: 'azonnal használatra készen, további konfiguráció nélkül',
        contextSentence: 'The official Postgres image works seamlessly out of the box.',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'chk_it_03',
        packId: 'pack_it_01',
        phrase: 'single source of truth',
        meaningHu: 'hiteles központi adatforrás / egyetlen hivatkozási pont',
        contextSentence: 'The Dockerfile acts as the single source of truth for the runtime environment.',
        createdAt: new Date().toISOString(),
      },
    ],
    contrastiveNotes: [
      {
        id: 'cn_it_01',
        packId: 'pack_it_01',
        hunglishTrap: 'running from Docker',
        correctUsage: 'running in Docker / running on Docker',
        explanationHu: 'Magyarul azt mondjuk: „Dockerből fut”, de angolban az „in” vagy „on” elöljárószót használjuk!',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'cn_it_02',
        packId: 'pack_it_01',
        hunglishTrap: 'compose the application',
        correctUsage: 'build / bundle the application',
        explanationHu: 'Bár a „Docker Compose” egy eszköz neve, az alkalmazás összeállítására a „build” vagy „package” igét használjuk.',
        createdAt: new Date().toISOString(),
      },
    ],
    exercises: [
      {
        id: 'ex_it_01',
        packId: 'pack_it_01',
        type: ExerciseType.CLOZE,
        prompt: 'Egészítsd ki a hiányzó szóval a mondatot:',
        payload: {
          sentenceWithGap: 'Docker allows developers to _______ applications in isolated environments.',
          options: ['isolate', 'isolated', 'isolating', 'isolation'],
        },
        solution: 'isolate',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'ex_it_02',
        packId: 'pack_it_01',
        type: ExerciseType.TRANSLATION_HU_TO_EN,
        prompt: 'Fordítsd le a kifejezést angolra (ügyelj a vonzatra!):',
        payload: {
          sourceHu: 'gyorsan elindítani egy új konténert',
          hints: ['spin', 'container'],
        },
        solution: 'spin up a new container',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'ex_it_03',
        packId: 'pack_it_01',
        type: ExerciseType.MULTIPLE_CHOICE,
        prompt: 'Melyik elöljárószó helyes a konténeres futtatásra?',
        payload: {
          question: 'The API service is currently running _______ a Docker container.',
          options: ['in', 'from', 'out', 'off'],
        },
        solution: 'in',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'ex_it_04',
        packId: 'pack_it_01',
        type: ExerciseType.MATCHING,
        prompt: 'Párosítsd az angol szakkifejezéseket a magyar jelentésükkel!',
        payload: {
          pairs: [
            { id: '1', left: 'container orchestration', right: 'konténer-vezénylés' },
            { id: '2', left: 'immutable infrastructure', right: 'módosíthatatlan infrastruktúra' },
            { id: '3', left: 'out of the box', right: 'azonnal használatra készen' },
          ],
        },
        solution: '1:konténer-vezénylés,2:módosíthatatlan infrastruktúra,3:azonnal használatra készen',
        createdAt: new Date().toISOString(),
      },
    ],
    readingMaterials: [
      {
        id: 'rm_it_01',
        packId: 'pack_it_01',
        title: 'Why Modern DevOps Relies on Containers',
        bodyText: 'Containerization has revolutionized software deployment workflows across the global technology landscape. By packaging software code together with all its runtime dependencies, libraries, and system configurations, Docker provides unprecedented consistency across development, staging, and production environments. Furthermore, container orchestration platforms like Kubernetes allow engineering teams to scale workloads dynamically with minimal operational overhead.',
        questions: [
          {
            question: 'What is the primary benefit of containerization highlighted in the passage?',
            options: ['Unprecedented consistency across all environments', 'Elimination of all coding errors', 'Free cloud hardware', 'No need for databases'],
            answer: 'Unprecedented consistency across all environments',
          },
          {
            question: 'What role do orchestration platforms like Kubernetes play?',
            options: ['They dynamically scale workloads with minimal overhead', 'They replace the Linux kernel', 'They rewrite Python into C++', 'They automate marketing'],
            answer: 'They dynamically scale workloads with minimal overhead',
          },
        ],
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'pack_biz_01',
    title: 'High-Stakes Negotiations & Strategic Dealmaking',
    cefr: CefrLevel.B2,
    topic: ZoneType.BUSINESS,
    focus: 'Negotiation, Legal Terms & Executive Communication',
    estimatedMinutes: 25,
    vocabularyCount: 3,
    chunksCount: 3,
    exercisesCount: 3,
    createdAt: new Date().toISOString(),
    writingPrompt: 'Write a 6-8 sentence negotiation follow-up email confirming mutual concessions and proposing next steps.',
    lessons: [
      {
        id: 'les_biz_01',
        packId: 'pack_biz_01',
        title: 'A sikeres tárgyalási retorika és a feltételes ajánlattétel',
        contentMd: `# Tárgyalástechnika és Diplomáciai Angol\n\nÜzleti tárgyalások során a magyar szakemberek gyakran túl direktnek tűnhetnek a közvetlen fordítások miatt. Az angolszász üzleti kultúrában a finomított nyelvezet (*hedging*), a feltételes módok (*conditionals*) és a professzionális kollokációk elengedhetetlenek.\n\n### Fő Tárgyalási Stratégiák:\n- **Feltételes ajánlatok:** *„If you could expedite delivery, we would be willing to commit to a larger volume.”*\n- **Konszenzus keresése:** *„Find common ground”* ahelyett, hogy merev pozíciókba merevednénk.\n- **Kölcsönös előnyök:** *„Win-win scenario”* és *„leverage”*.`,
        createdAt: new Date().toISOString(),
      },
    ],
    vocabulary: [
      {
        id: 'voc_biz_01',
        packId: 'pack_biz_01',
        term: 'leverage',
        phonetics: '/ˈliː.vər.ɪdʒ/',
        translationHu: 'tárgyalási pozíció / alkualap / előny kihasználása',
        definitionEn: 'Power to influence people and get the results you want.',
        collocations: ['gain leverage', 'negotiating leverage', 'leverage expertise'],
        examples: ['Our proprietary patent gives us significant leverage in licensing talks.'],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'voc_biz_02',
        packId: 'pack_biz_01',
        term: 'concession',
        phonetics: '/kənˈseʃ.ən/',
        translationHu: 'engedmény, kompromisszum',
        definitionEn: 'Something that is allowed or given up, often in order to end a disagreement.',
        collocations: ['make concessions', 'mutual concessions', 'seek a concession'],
        examples: ['Both parties had to make mutual concessions to finalize the contract.'],
        createdAt: new Date().toISOString(),
      },
      {
        id: 'voc_biz_03',
        packId: 'pack_biz_01',
        term: 'deadlock',
        phonetics: '/ˈded.lɒk/',
        translationHu: 'holtponthoz jutás, patthelyzet',
        definitionEn: 'A situation in which no progress can be made.',
        collocations: ['break the deadlock', 'reach a deadlock', 'avoid deadlock'],
        examples: ['A neutral mediator was called in to break the deadlock.'],
        createdAt: new Date().toISOString(),
      },
    ],
    chunks: [
      {
        id: 'chk_biz_01',
        packId: 'pack_biz_01',
        phrase: 'find common ground',
        meaningHu: 'közös nevezőt találni',
        contextSentence: 'Despite initial friction, we managed to find common ground on pricing.',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'chk_biz_02',
        packId: 'pack_biz_01',
        phrase: 'on the table',
        meaningHu: 'napirenden lenni / tárgyalási opcióként szerepelni',
        contextSentence: 'A 15% volume discount is currently on the table.',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'chk_biz_03',
        packId: 'pack_biz_01',
        phrase: 'bottom line',
        meaningHu: 'a lényeg / a végső eredmény / a pénzügyi nettó',
        contextSentence: 'The bottom line is that the contract must be profitable for both sides.',
        createdAt: new Date().toISOString(),
      },
    ],
    contrastiveNotes: [
      {
        id: 'cn_biz_01',
        packId: 'pack_biz_01',
        hunglishTrap: 'I suggest you to accept',
        correctUsage: 'I suggest that you accept / I suggest accepting',
        explanationHu: 'A „suggest” igét sosem követi közvetlen infinitív „to” szerkezettel! Helyes: „I suggest that you accept”.',
        createdAt: new Date().toISOString(),
      },
    ],
    exercises: [
      {
        id: 'ex_biz_01',
        packId: 'pack_biz_01',
        type: ExerciseType.CLOZE,
        prompt: 'Válaszd ki a tárgyalási kollokációt kiegészítő szót:',
        payload: {
          sentenceWithGap: 'After three hours of debate, the executives finally reached a _______ and signed.',
          options: ['compromise', 'deadlock', 'concession', 'leverage'],
        },
        solution: 'compromise',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'ex_biz_02',
        packId: 'pack_biz_01',
        type: ExerciseType.TRANSLATION_HU_TO_EN,
        prompt: 'Fordítsd le angolra a kifejezést:',
        payload: {
          sourceHu: 'közös nevezőt találni',
          hints: ['common', 'ground'],
        },
        solution: 'find common ground',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'ex_biz_03',
        packId: 'pack_biz_01',
        type: ExerciseType.MULTIPLE_CHOICE,
        prompt: 'Melyik a nyelvtanilag helyes javaslattétel?',
        payload: {
          question: 'Which sentence correctly uses the verb "suggest"?',
          options: [
            'I suggest that we review the contract terms.',
            'I suggest you to review the contract terms.',
            'I suggest for you to review terms.',
            'I suggest us to review terms.',
          ],
        },
        solution: 'I suggest that we review the contract terms.',
        createdAt: new Date().toISOString(),
      },
    ],
    readingMaterials: [],
  },
  {
    id: 'pack_eve_01',
    title: 'Pub Culture, Social Nuances & Fluid Small Talk',
    cefr: CefrLevel.B1,
    topic: ZoneType.EVERYDAY,
    focus: 'Social Interactions, Idioms & Conversational Agility',
    estimatedMinutes: 20,
    vocabularyCount: 2,
    chunksCount: 2,
    exercisesCount: 2,
    createdAt: new Date().toISOString(),
    writingPrompt: 'Write a friendly email inviting a friend to a local weekend gathering.',
    lessons: [
      {
        id: 'les_eve_01',
        packId: 'pack_eve_01',
        title: 'Hogyan csevegjünk természetesen kínos csendek nélkül?',
        contentMd: `# A Hétköznapi Csevegés Művészete\n\nA magyar beszélők gyakran túl direkt választ adnak a formális udvariassági kérdésekre. Például a *„How do you do?”* nem a fizikai állapotod felőli érdeklődés, hanem egy formális köszöntés!\n\n### Aranyszabályok:\n- **Kérdezz vissza:** Ne csak válaszolj, mindig dobj vissza egy nyitott kérdést (*„How about yourself?”*).\n- **Időjárás és utazás:** A tökéletes jégtörők (*icebreakers*).\n- **Természetes visszajelzések:** *„Is that so?”*, *„Fair enough!”*, *„Tell me about it!”*`,
        createdAt: new Date().toISOString(),
      },
    ],
    vocabulary: [
      {
        id: 'voc_eve_01',
        packId: 'pack_eve_01',
        term: 'catch up',
        phonetics: '/kætʃ ʌp/',
        translationHu: 'utoléri magát, megbeszélik a friss híreket',
        definitionEn: 'To talk with someone you have not seen for a while to find out what they have been doing.',
        collocations: ['catch up over coffee', 'catch up on news', 'play catch up'],
        examples: ['Let us grab a pint and catch up on everything that happened this week.'],
        createdAt: new Date().toISOString(),
      },
    ],
    chunks: [
      {
        id: 'chk_eve_01',
        packId: 'pack_eve_01',
        phrase: 'speak of the devil',
        meaningHu: 'farkast emlegetnek (épp most érkezett)',
        contextSentence: 'Speak of the devil! We were just talking about your new promotion.',
        createdAt: new Date().toISOString(),
      },
    ],
    contrastiveNotes: [
      {
        id: 'cn_eve_01',
        packId: 'pack_eve_01',
        hunglishTrap: 'How do you say in English...?',
        correctUsage: 'How do you say ... in English? / What is the English word for...?',
        explanationHu: 'A magyar szórendet nem szabad lemásolni! Az „in English” mindig a mondat végére kerül.',
        createdAt: new Date().toISOString(),
      },
    ],
    exercises: [
      {
        id: 'ex_eve_01',
        packId: 'pack_eve_01',
        type: ExerciseType.CLOZE,
        prompt: 'Válaszd ki az idiómát:',
        payload: {
          sentenceWithGap: 'Her face certainly _______ a bell, but I forgot her name.',
          options: ['rings', 'strikes', 'sounds', 'tolls'],
        },
        solution: 'rings',
        createdAt: new Date().toISOString(),
      },
      {
        id: 'ex_eve_02',
        packId: 'pack_eve_01',
        type: ExerciseType.TRANSLATION_HU_TO_EN,
        prompt: 'Fordítsd le a kifejezést:',
        payload: {
          sourceHu: 'ismerősen cseng',
          hints: ['ring', 'bell'],
        },
        solution: 'ring a bell',
        createdAt: new Date().toISOString(),
      },
    ],
    readingMaterials: [],
  },
  {
    id: 'pack_acad_01',
    title: 'Analytical Argumentation, Hedging & Academic Synthesis',
    cefr: CefrLevel.C1,
    topic: ZoneType.ACADEMIC,
    focus: 'Formal Essays, Critical Thinking & Rhetorical Precision',
    estimatedMinutes: 35,
    vocabularyCount: 1,
    chunksCount: 1,
    exercisesCount: 1,
    createdAt: new Date().toISOString(),
    writingPrompt: 'Write a short academic critique of modern AI tools in education.',
    lessons: [
      {
        id: 'les_acad_01',
        packId: 'pack_acad_01',
        title: 'Akadémiai távolságtartás (Hedging) és szintézis',
        contentMd: `# Tudományos Szövegalkotás és Érvelés\n\nC1 szinten elvárás, hogy a tanuló ne tegyen kategorikus, túlzó kijelentéseket (*overstatements*), hanem alkalmazzon árnyalt modális eszközöket (*hedging devices*).\n\n### Példák:\n- **Kategorikus:** *„This proves that AI is dangerous.”* ❌\n- **Akadémiailag árnyalt:** *„These empirical findings suggest that rapid AI adoption may entail unprecedented systemic risks.”* ✅`,
        createdAt: new Date().toISOString(),
      },
    ],
    vocabulary: [
      {
        id: 'voc_acad_01',
        packId: 'pack_acad_01',
        term: 'substantiate',
        phonetics: '/səbˈstæn.ʃi.eɪt/',
        translationHu: 'alátámaszt, igazol (tényekkel/bizonyítékkal)',
        definitionEn: 'To provide evidence to support or prove the truth of something.',
        collocations: ['substantiate a claim', 'substantiate allegations', 'empirical evidence to substantiate'],
        examples: ['The researcher presented statistical data to substantiate her hypothesis.'],
        createdAt: new Date().toISOString(),
      },
    ],
    chunks: [
      {
        id: 'chk_acad_01',
        packId: 'pack_acad_01',
        phrase: 'corroborate the findings',
        meaningHu: 'megerősíteni a kutatási eredményeket',
        contextSentence: 'Further peer-reviewed studies are needed to corroborate these initial findings.',
        createdAt: new Date().toISOString(),
      },
    ],
    contrastiveNotes: [
      {
        id: 'cn_acad_01',
        packId: 'pack_acad_01',
        hunglishTrap: 'on the other side',
        correctUsage: 'on the other hand / conversely',
        explanationHu: 'A magyar „másrészt” kifejezés angolul „on the other hand”, nem „on the other side”.',
        createdAt: new Date().toISOString(),
      },
    ],
    exercises: [
      {
        id: 'ex_acad_01',
        packId: 'pack_acad_01',
        type: ExerciseType.CLOZE,
        prompt: 'Válaszd ki az akadémiai kifejezést:',
        payload: {
          sentenceWithGap: 'Additional empirical research is required to _______ the theoretical framework.',
          options: ['substantiate', 'substance', 'substantial', 'substantiating'],
        },
        solution: 'substantiate',
        createdAt: new Date().toISOString(),
      },
    ],
    readingMaterials: [],
  },
];

export const INITIAL_WRITING_SUBMISSIONS: WritingSubmissionModel[] = [
  {
    id: 'sub_01',
    userId: INITIAL_USER.id,
    promptText: 'Explain why containerization is essential in modern cloud architecture.',
    submittedText: 'In modern DevOps, running application in Docker is very popular. According to me, it helps developers to isolate dependencies and make a faster deployment without overhead.',
    aiScore: 84,
    aiFeedback: {
      score: 84,
      overallAssessmentHu: 'Kifejezetten jó gondolatmenet és választékos témaköri szókincs. Néhány magyaros tükörfordítás (különösen az "according to me") finomításával még természetesebb lesz a szöveged.',
      errors: [
        {
          original: 'According to me',
          replacement: 'In my opinion / From my perspective',
          explanationHu: 'Az "according to me" magyar tükörfordítás. Angolban külső forrásokra hivatkozunk "according to"-val.',
          ruleHu: 'Véleménykifejezés elöljárószavai',
        },
        {
          original: 'running application',
          replacement: 'running applications / running an application',
          explanationHu: 'A számlálható főnevek (application) egyes számban névelőt igényelnek, vagy többes számba kell tenni őket.',
          ruleHu: 'Névelőhasználat számlálható főneveknél',
        },
      ],
      positives: ['Helyes "isolate dependencies" kollokáció', 'Jó "without overhead" terminológia'],
      suggestedCefr: CefrLevel.B2,
    },
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
];
